baseURL = "https://bretwardjames.com/"
languageCode = "en-us"
title = "Bretward James"
theme = "uilite"
disableKinds = ['taxonomy', 'taxonomyTerm']
enableEmoji = "true"

[outputs]
home = [ "HTML", "RSS"]
blog = [ "HTML", "RSS"]
stuff = [ "HTML", "RSS"]