# Site settings
baseURL = "https://bretwardjames.co"
languageCode = "en-US"
title = "Bret Martineau"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2019 Bret Martineau"

[params]

  # Metadata for search engines and social sharing
  author = "Bret Martineau"
  description = "Bret Martineau is a tech junkie, an armchair philosopher, a semi-professional photographer, an amateur thai boxer, and a complete nerd."
  shareImage = "images/profilepic.jpg"
  twitterHandle = "bretwardjames"

  # Favicon
  favicon = "beard.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/profilepic.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Blog"
        url = "https://medium.com/@bretwardjames"

      [[params.links.list1.link]]
        text = "Email"
        url = "mailto:bretwardjames@gmail.com"

      [[params.links.list1.link]]
        text = "LinkedIn"
        url = "https://linkedin.com/in/bretwardjames"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Twitter"
        url = "https://twitter.com/bretwardjames"

      [[params.links.list2.link]]
        text = "Instagram"
        url = "https://instagram.com/bretwardjames"

      [[params.links.list2.link]]
        text = "Facebook"
        url = "https://facebook.com/bretwardjames"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Stuff"

      [[params.links.list3.link]]
        text = "Martin O'Foto"
        url = "https://martin-ofoto.com"

      [[params.links.list3.link]]
        text = "YouTube"
        url = "https://youtube.com/bretwardjames"

      [[params.links.list3.link]]
        text = "SoundCloud"
        url = "https://soundcloud.com/bretwardjames"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
