[context.production.environment]
HUGO_VERSION = "0.54.0"
HUGO_ENV = "production"

[[redirects]]
  from = "https://bretmartineau.com/*"
  to = "https://bretwardjames.com/:splat"
  force = true
  status = 301

[[redirects]]
  from = "/morningcoffee"
  to = "/blog/infusionsoft-the-early-days-morning-coffee-16/"
  force = true
  status = 301

[[redirects]]
  from = "/assassin"
  to = "/blog/a-conversation-with-an-assassin-vol-1/"
  force = true
  status = 301