[context.production.environment]
HUGO_VERSION = "0.54.0"
HUGO_ENV = "production"

[[redirects]]
  from = "https://bretmartineau.com/*"
  to = "https://bretwardjames.com/:splat"
  force = true
  status = 301

