[context.production.environment]
HUGO_VERSION = "0.54.0"
HUGO_ENV = "production"

[[redirects]]
  from = "https://bretmartineau.com/*"
  to = "https://bretwardjames.com/:splat"
  force = true
  status = 301

[[redirects]]
  from = "/morningcoffee"
  to = "/blog/infusionsoft-the-early-days-morning-coffee-16/"
  force = true
  status = 301

[[redirects]]
  from = "/assassin"
  to = "/blog/a-conversation-with-an-assassin-vol-1/"
  force = true
  status = 301

[[redirects]]
  from = "/photo"
  to = "https://bretwardjames.myportfolio.com"
  force = true
  status = 301

[[redirects]]
  from = "/plusthis"
  to = "https://plusthis.com?ac=zp3h19"
  force = true
  status = 301

[[redirects]]
  from = "/monkeypod"
  to = "https://cr984.isrefer.com/go/courses/wunntee"
  force = true
  status = 301

[[redirects]]
  from = "/picsnippets"
  to = "https://www.picsnippets.com?afmc=6d"
  force = true
  status = 301